language: emacs-lisp
before_install:
  # Install Emacs
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs
  # Install Cask
  - git clone --depth=1 https://github.com/cask/cask.git ~/.cask
  - export PATH="~/.cask/bin:$PATH"
  - cask
install:
  # Install your dependencies
  - cask install
script:
  make
